import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ItemMenu from "@/components/ItemMenu";
import { FcCalendar, FcHome } from "react-icons/fc";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <aside className="w-60 bg-[#9d07d1] text-white h-full fixed">
          <ul>
            <ItemMenu url={"/"} title="Início" icon={<FcHome size={26} />} />
            <ItemMenu
              url={"/reservations"}
              title="Minhas reservas"
              icon={<FcCalendar size={26} />}
            />
          </ul>
        </aside>
        <main className="ml-72 flex-1">{children}</main>
        <ToastContainer />
      </body>
    </html>
  );
}
